### ISSUE TITLE
새로 설치했는데... 저번과 비슷한 문제가 있네요... 또 올레쪽에서 무언가를 바꾼거 같습니다.

### ISSUE THREAD

**Issue by rubyon** [soju6jan/KLive#27]
저번과 같은 증상입니다.

에러 메세지는 아래와 같습니다.

올레에서 뭘 하는건지... 일시적인 건지... 아니면 또 뭐를 바꾼건지... ㅠㅠ

WSGIServer start..
Traceback (most recent call last):
  File "kliveProxy.py", line 97, in thread_main
    MakeM3U(prefix_m3u)
  File "/klive_server/klive.py", line 35, in MakeM3U
    if item == 'OLLEH': str += OLLEH().MakeM3U(url)
  File "/klive_server/lib/olleh.py", line 118, in MakeM3U
    list = self.GetChannelList()
  File "/klive_server/lib/olleh.py", line 77, in GetChannelList
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by rubyon** [comment]
user agent 가 블럭당한것 같습니다.

	USER_AGENT = 'OMS (compatible;ServiceType/OTM;DeviceType/WIN8PAD;DeviceModel/AllSeries;OSType/WINM;OSVersion/8.1.0;AppVersion/1.2.1.9))'

요부분에서 마지막 앱 버전을 살짝 바꿔주니 에러 안나고 m3u 생성해내고 있네요

**Comment by rubyon** [comment]
다방면으로 테스트해본결과

아이폰 올레티비 모바일 앱이 와이파이로 접속하면 먹통입니다 (서버와 같은 대역)
LTE 는 접속이 됩니다

왠지 ip 블락 인거 같네요 흠...

대단하네요 kt

**Comment by soju6jan** [comment]
오타가 있었습니다.
더 타이트하게 체크하는 건 확실해 보입니다.
