### ISSUE TITLE
m3upipe 사용 문의 드립니다.

### ISSUE THREAD

**Issue by pms0811** [soju6jan/KLive#4]
안녕하세요. soju6jan님.

좋은 프로그램 만들어 주셔서 잘 써볼려고 하는데 잘 안되는 점이 있어
질문만 계속 드리게 되어 죄송합니다.
eddylab 카페 댓글은 잘 안보시는것 같아 여기 직접 글을 남깁니다.

우선 m3upipe 를 사용하여 tvheadend에서 등록은 하였습니다.
tvheadend 버전 4.3.28042017에서는 2초 재생후 멈춤현상 때문에 
tvheadend 버전 4.1.1595에서 등록을 하였습니다.
(헤놀에서 패키지 설치라 여러 버전을 테스트 못해보고 두가지만 해볼수 있었습니다.)
(klive는 해놀에서 도커상에 설치 하였습니다.)

MUX 등록시에
pipe://ffmpeg -i http://IP:PORT/url?mode=url&type=OKSUSU&id=240 -c copy -f mpegts pipe:1
이렇게 등록을 하면 채널검색 실패가 됩니다. (tvheadend 버전에 상관없이)
그런데
pipe://ffmpeg -i http://IP:PORT/url?mode=url&type=OKSUSU&id=240 -c copy -f mpegts pipe:1_
(_는 공란.)(제일 마지막에 공란 추가)
이렇게 등록을 하면 잘 됩니다.
옥수수 채널만 태스트 해보았습니다.

여기서 문제가 시간이 좀 지나면 재생이 안되는데 
그때 tvheadend에 들어가서 보면 주소등록창에 공란이 없는 상태로 되어있습니다.
이때는 주소 수정을 아무리 해도 공란이 안생기고 MUX를 지우고 새로 생성해야지만 됩니다.

시간나실때 수정 한번만 더 부탁드립니다.

**Comment by pms0811** [comment]
No JSON object could be decoded
'NoneType' object has no attribute '__getitem__'
TYPE : OKSUSU
ID : 240
URL : None
[2018-12-12 07:30:59,165] ERROR in app: Exception on /url [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
172.17.42.1 - - [2018-12-12 07:30:59] "GET /url?mode=url&type=OKSUSU&id=240 HTTP/1.1" 500 412 0.017245

재생이 안될때 나오는 메세지입니다.

kodi 옥수수 애드온에서 재생이 안될때
GetURL: 'NoneType' object has no attribute 'getitem'

klive 에서 재생이 안될때
'NoneType' object has no attribute '__getitem__'

비슷한 문제가 아닐까 생각됩니다.
